version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: siavash
    ports:
      - "33063:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

