---
- name: limits.conf
  ansible.builtin.template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root

- name: coredump.conf
  ansible.builtin.template:
    src: coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
