---
- hosts: all
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: preparing and hardening playbook 
  roles:
  # preparing server and hardening
    - { role: roles/preparing, become: True, tags: preparing }
