- hosts: all
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: Setup traefik for reverse proxy
  roles:
    - { role: roles/traefik, bcome: True, tags: traefik_setup }
