"""empty message

Revision ID: dd043b884357
Revises: 
Create Date: 2024-08-10 17:17:30.757969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd043b884357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_url'), ['url'], unique=False)

    op.drop_table('help_relation')
    op.drop_table('plugin')
    op.drop_table('tables_priv')
    op.drop_table('global_grants')
    op.drop_table('replication_asynchronous_connection_failover')
    op.drop_table('servers')
    op.drop_table('time_zone_leap_second')
    op.drop_table('innodb_table_stats')
    op.drop_table('server_cost')
    op.drop_table('time_zone_name')
    op.drop_table('user')
    op.drop_table('slave_worker_info')
    op.drop_table('replication_group_configuration_version')
    with op.batch_alter_table('help_category', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_category')
    op.drop_table('db')
    with op.batch_alter_table('help_topic', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_topic')
    op.drop_table('slave_relay_log_info')
    op.drop_table('replication_asynchronous_connection_failover_managed')
    op.drop_table('columns_priv')
    op.drop_table('role_edges')
    op.drop_table('procs_priv')
    op.drop_table('innodb_index_stats')
    op.drop_table('gtid_executed')
    op.drop_table('slave_master_info')
    op.drop_table('engine_cost')
    op.drop_table('slow_log')
    op.drop_table('general_log')
    op.drop_table('time_zone_transition')
    op.drop_table('time_zone_transition_type')
    op.drop_table('password_history')
    op.drop_table('ndb_binlog_index')
    op.drop_table('replication_group_member_actions')
    op.drop_table('time_zone')
    op.drop_table('default_roles')
    op.drop_table('proxies_priv')
    op.drop_table('func')
    op.drop_table('component')
    with op.batch_alter_table('help_keyword', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_keyword',
    sa.Column('help_keyword_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id'),
    comment='help keywords',
    mysql_comment='help keywords',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('help_keyword', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('component',
    sa.Column('component_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('component_group_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('component_urn', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('component_id'),
    comment='Components',
    mysql_comment='Components',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('func',
    sa.Column('name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('ret', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dl', mysql.CHAR(collation='utf8mb3_bin', length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('function', 'aggregate'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    comment='User defined functions',
    mysql_collate='utf8mb3_bin',
    mysql_comment='User defined functions',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.VARCHAR(collation='utf8mb3_bin', length=288), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    comment='User proxy privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('default_roles',
    sa.Column('HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('DEFAULT_ROLE_HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("'%%'"), nullable=False),
    sa.Column('DEFAULT_ROLE_USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('HOST', 'USER', 'DEFAULT_ROLE_HOST', 'DEFAULT_ROLE_USER'),
    comment='Default roles',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Default roles',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Use_leap_seconds', mysql.ENUM('Y', 'N'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id'),
    comment='Time zones',
    mysql_comment='Time zones',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('replication_group_member_actions',
    sa.Column('name', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=False, comment='The action name.'),
    sa.Column('event', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False, comment='The event that will trigger the action.'),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Whether the action is enabled.'),
    sa.Column('type', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False, comment='The action type.'),
    sa.Column('priority', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False, comment='The order on which the action will be run, value between 1 and 100, lower values first.'),
    sa.Column('error_handling', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False, comment='On errors during the action will be handled: IGNORE, CRITICAL.'),
    sa.PrimaryKeyConstraint('name', 'event'),
    comment='The member actions configuration.',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='The member actions configuration.',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ndb_binlog_index',
    sa.Column('Position', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('File', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('epoch', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('inserts', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('updates', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('deletes', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('schemaops', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('orig_server_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('orig_epoch', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('gci', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('next_position', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('next_file', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('epoch', 'orig_server_id', 'orig_epoch'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('password_history',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Password_timestamp', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('Password', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User', 'Password_timestamp'),
    comment='Password history for user accounts',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Password history for user accounts',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_transition_type',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Offset', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Is_DST', mysql.TINYINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Abbreviation', mysql.CHAR(length=8), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_type_id'),
    comment='Time zone transition types',
    mysql_comment='Time zone transition types',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    comment='Time zone transitions',
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('general_log',
    sa.Column('event_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('command_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('argument', mysql.MEDIUMBLOB(), nullable=False),
    comment='General log',
    mysql_comment='General log',
    mysql_default_charset='utf8mb3',
    mysql_engine='CSV'
    )
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('lock_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    comment='Slow log',
    mysql_comment='Slow log',
    mysql_default_charset='utf8mb3',
    mysql_engine='CSV'
    )
    op.create_table('engine_cost',
    sa.Column('engine_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('device_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('cost_value', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('default_value', mysql.FLOAT(), sa.Computed("((case `cost_name` when _utf8mb3'io_block_read_cost' then 1.0 when _utf8mb3'memory_block_read_cost' then 0.25 else NULL end))", persisted=False), nullable=True),
    sa.PrimaryKeyConstraint('cost_name', 'engine_name', 'device_type'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('slave_master_info',
    sa.Column('Number_of_lines', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='Number of lines in the file.'),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=False, comment='The name of the master binary log currently being read from the master.'),
    sa.Column('Master_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='The master log position of the last read event.'),
    sa.Column('Host', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=True, comment='The host name of the source.'),
    sa.Column('User_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The user name used to connect to the master.'),
    sa.Column('User_password', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The password used to connect to the master.'),
    sa.Column('Port', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='The network port used to connect to the master.'),
    sa.Column('Connect_retry', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='The period (in seconds) that the slave will wait before trying to reconnect to the master.'),
    sa.Column('Enabled_ssl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Indicates whether the server supports SSL connections.'),
    sa.Column('Ssl_ca', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The file used for the Certificate Authority (CA) certificate.'),
    sa.Column('Ssl_capath', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The path to the Certificate Authority (CA) certificates.'),
    sa.Column('Ssl_cert', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The name of the SSL certificate file.'),
    sa.Column('Ssl_cipher', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The name of the cipher in use for the SSL connection.'),
    sa.Column('Ssl_key', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The name of the SSL key file.'),
    sa.Column('Ssl_verify_server_cert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Whether to verify the server certificate.'),
    sa.Column('Heartbeat', mysql.FLOAT(), nullable=False),
    sa.Column('Bind', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='Displays which interface is employed when connecting to the MySQL server'),
    sa.Column('Ignored_server_ids', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The number of server IDs to be ignored, followed by the actual server IDs'),
    sa.Column('Uuid', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The master server uuid.'),
    sa.Column('Retry_count', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='Number of reconnect attempts, to the master, before giving up.'),
    sa.Column('Ssl_crl', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The file used for the Certificate Revocation List (CRL)'),
    sa.Column('Ssl_crlpath', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The path used for Certificate Revocation List (CRL) files'),
    sa.Column('Enabled_auto_position', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Indicates whether GTIDs will be used to retrieve events from the master.'),
    sa.Column('Channel_name', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The channel on which the replica is connected to a source. Used in Multisource Replication'),
    sa.Column('Tls_version', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='Tls version'),
    sa.Column('Public_key_path', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The file containing public key of master server.'),
    sa.Column('Get_public_key', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Preference to get public key from master.'),
    sa.Column('Network_namespace', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='Network namespace used for communication with the master server.'),
    sa.Column('Master_compression_algorithm', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=64), nullable=False, comment='Compression algorithm supported for data transfer between source and replica.'),
    sa.Column('Master_zstd_compression_level', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='Compression level associated with zstd compression algorithm.'),
    sa.Column('Tls_ciphersuites', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='Ciphersuites used for TLS 1.3 communication with the master server.'),
    sa.Column('Source_connection_auto_failover', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Indicates whether the channel connection failover is enabled.'),
    sa.Column('Gtid_only', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Indicates if this channel only uses GTIDs and does not persist positions.'),
    sa.PrimaryKeyConstraint('Channel_name'),
    comment='Master Information',
    mysql_comment='Master Information',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('gtid_executed',
    sa.Column('source_uuid', mysql.CHAR(length=36), nullable=False, comment='uuid of the source where the transaction was originally executed.'),
    sa.Column('interval_start', mysql.BIGINT(), autoincrement=False, nullable=False, comment='First number of interval.'),
    sa.Column('interval_end', mysql.BIGINT(), autoincrement=False, nullable=False, comment='Last number of interval.'),
    sa.Column('gtid_tag', mysql.CHAR(length=32), nullable=False, comment='GTID Tag.'),
    sa.PrimaryKeyConstraint('source_uuid', 'gtid_tag', 'interval_start'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('innodb_index_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('index_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stat_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('stat_value', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sample_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('stat_description', mysql.VARCHAR(collation='utf8mb3_bin', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name', 'index_name', 'stat_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('procs_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_type', mysql.ENUM('FUNCTION', 'PROCEDURE'), nullable=False),
    sa.Column('Grantor', mysql.VARCHAR(collation='utf8mb3_bin', length=288), server_default=sa.text("''"), nullable=False),
    sa.Column('Proc_priv', mysql.SET('Execute', 'Alter Routine', 'Grant', charset='utf8mb3', collation='utf8mb3_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db', 'Routine_name', 'Routine_type'),
    comment='Procedure privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Procedure privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('role_edges',
    sa.Column('FROM_HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('FROM_USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('WITH_ADMIN_OPTION', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('FROM_HOST', 'FROM_USER', 'TO_HOST', 'TO_USER'),
    comment='Role hierarchy and role grants',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Role hierarchy and role grants',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('columns_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Column_priv', mysql.SET('Select', 'Insert', 'Update', 'References', charset='utf8mb3', collation='utf8mb3_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db', 'Table_name', 'Column_name'),
    comment='Column privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Column privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('replication_asynchronous_connection_failover_managed',
    sa.Column('Channel_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The replication channel name that connects source and replica.'),
    sa.Column('Managed_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='The name of the source which needs to be managed.'),
    sa.Column('Managed_type', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='Determines the managed type.'),
    sa.Column('Configuration', mysql.JSON(), nullable=True, comment='The data to help manage group. For Managed_type = GroupReplication, Configuration value should contain {"Primary_weight": 80, "Secondary_weight": 60}, so that it assigns weight=80 to PRIMARY of the group, and weight=60 for rest of the members in mysql.replication_asynchronous_connection_failover table.'),
    sa.PrimaryKeyConstraint('Channel_name', 'Managed_name'),
    comment='The managed source configuration details',
    mysql_comment='The managed source configuration details',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('slave_relay_log_info',
    sa.Column('Number_of_lines', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='Number of lines in the file or rows in the table. Used to version table definitions.'),
    sa.Column('Relay_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The name of the current relay log file.'),
    sa.Column('Relay_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True, comment='The relay log position of the last executed event.'),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='The name of the master binary log file from which the events in the relay log file were read.'),
    sa.Column('Master_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True, comment='The master log position of the last executed event.'),
    sa.Column('Sql_delay', mysql.INTEGER(), autoincrement=False, nullable=True, comment='The number of seconds that the slave must lag behind the master.'),
    sa.Column('Number_of_workers', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True, comment='Internal Id that uniquely identifies this record.'),
    sa.Column('Channel_name', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The channel on which the replica is connected to a source. Used in Multisource Replication'),
    sa.Column('Privilege_checks_username', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=32), nullable=True, comment='Username part of PRIVILEGE_CHECKS_USER.'),
    sa.Column('Privilege_checks_hostname', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=True, comment='Hostname part of PRIVILEGE_CHECKS_USER.'),
    sa.Column('Require_row_format', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Indicates whether the channel shall only accept row based events.'),
    sa.Column('Require_table_primary_key_check', mysql.ENUM('STREAM', 'ON', 'OFF', 'GENERATE'), server_default=sa.text("'STREAM'"), nullable=False, comment='Indicates what is the channel policy regarding tables without primary keys on create and alter table queries'),
    sa.Column('Assign_gtids_to_anonymous_transactions_type', mysql.ENUM('OFF', 'LOCAL', 'UUID'), server_default=sa.text("'OFF'"), nullable=False, comment='Indicates whether the channel will generate a new GTID for anonymous transactions. OFF means that anonymous transactions will remain anonymous. LOCAL means that anonymous transactions will be assigned a newly generated GTID based on server_uuid. UUID indicates that anonymous transactions will be assigned a newly generated GTID based on Assign_gtids_to_anonymous_transactions_value'),
    sa.Column('Assign_gtids_to_anonymous_transactions_value', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=True, comment='Indicates the UUID used while generating GTIDs for anonymous transactions'),
    sa.PrimaryKeyConstraint('Channel_name'),
    comment='Relay Log Information',
    mysql_comment='Relay Log Information',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('help_topic',
    sa.Column('help_topic_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('help_category_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('example', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_topic_id'),
    comment='help topics',
    mysql_comment='help topics',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('help_topic', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('db',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db'),
    comment='Database privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    comment='help categories',
    mysql_comment='help categories',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('help_category', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('replication_group_configuration_version',
    sa.Column('name', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=False, comment='The configuration name.'),
    sa.Column('version', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='The version of the configuration name.'),
    sa.PrimaryKeyConstraint('name'),
    comment='The group configuration version.',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='The group configuration version.',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('slave_worker_info',
    sa.Column('Id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Relay_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=False),
    sa.Column('Relay_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=False),
    sa.Column('Master_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_relay_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=False),
    sa.Column('Checkpoint_relay_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_master_log_name', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_bin'), nullable=False),
    sa.Column('Checkpoint_master_log_pos', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_seqno', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_group_size', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_group_bitmap', sa.BLOB(), nullable=False),
    sa.Column('Channel_name', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The channel on which the replica is connected to a source. Used in Multisource Replication'),
    sa.PrimaryKeyConstraint('Channel_name', 'Id'),
    comment='Worker Information',
    mysql_comment='Worker Information',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("'caching_sha2_password'"), nullable=False),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.Column('password_expired', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('password_last_changed', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password_lifetime', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account_locked', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_role_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_role_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Password_reuse_history', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_reuse_time', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_require_current', mysql.ENUM('N', 'Y'), nullable=True),
    sa.Column('User_attributes', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User'),
    comment='Users and global privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    comment='Time zone names',
    mysql_comment='Time zone names',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('server_cost',
    sa.Column('cost_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('cost_value', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('default_value', mysql.FLOAT(), sa.Computed("((case `cost_name` when _utf8mb3'disk_temptable_create_cost' then 20.0 when _utf8mb3'disk_temptable_row_cost' then 0.5 when _utf8mb3'key_compare_cost' then 0.05 when _utf8mb3'memory_temptable_create_cost' then 1.0 when _utf8mb3'memory_temptable_row_cost' then 0.1 when _utf8mb3'row_evaluate_cost' then 0.1 else NULL end))", persisted=False), nullable=True),
    sa.PrimaryKeyConstraint('cost_name'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('innodb_table_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('n_rows', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('clustered_index_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sum_of_other_index_sizes', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    comment='Leap seconds information for time zones',
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('servers',
    sa.Column('Server_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Username', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Port', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Socket', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Wrapper', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Owner', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Server_name'),
    comment='MySQL Foreign Servers table',
    mysql_comment='MySQL Foreign Servers table',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('replication_asynchronous_connection_failover',
    sa.Column('Channel_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The replication channel name that connects source and replica.'),
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=False, comment='The source hostname that the replica will attempt to switch over the replication connection to in case of a failure.'),
    sa.Column('Port', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='The source port that the replica will attempt to switch over the replication connection to in case of a failure.'),
    sa.Column('Network_namespace', mysql.CHAR(length=64), nullable=False, comment='The source network namespace that the replica will attempt to switch over the replication connection to in case of a failure. If its value is empty, connections use the default (global) namespace.'),
    sa.Column('Weight', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False, comment='The order in which the replica shall try to switch the connection over to when there are failures. Weight can be set to a number between 1 and 100, where 100 is the highest weight and 1 the lowest.'),
    sa.Column('Managed_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='The name of the group which this server belongs to.'),
    sa.PrimaryKeyConstraint('Channel_name', 'Host', 'Port', 'Network_namespace', 'Managed_name'),
    comment='The source configuration details',
    mysql_comment='The source configuration details',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('global_grants',
    sa.Column('USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('PRIV', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('WITH_GRANT_OPTION', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('USER', 'HOST', 'PRIV'),
    comment='Extended global grants',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Extended global grants',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('tables_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Grantor', mysql.VARCHAR(collation='utf8mb3_bin', length=288), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Table_priv', mysql.SET('Select', 'Insert', 'Update', 'Delete', 'Create', 'Drop', 'Grant', 'References', 'Index', 'Alter', 'Create View', 'Show view', 'Trigger', charset='utf8mb3', collation='utf8mb3_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_priv', mysql.SET('Select', 'Insert', 'Update', 'References', charset='utf8mb3', collation='utf8mb3_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db', 'Table_name'),
    comment='Table privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Table privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('plugin',
    sa.Column('name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('dl', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    comment='MySQL plugins',
    mysql_comment='MySQL plugins',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('help_relation',
    sa.Column('help_topic_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('help_keyword_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id', 'help_topic_id'),
    comment='keyword-topic relation',
    mysql_comment='keyword-topic relation',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_url'))
        batch_op.drop_index(batch_op.f('ix_repositories_owner'))

    op.drop_table('repositories')
    # ### end Alembic commands ###
